<form id="form-ejemplo" class="well form-horizontal" role="form" method="post" action="<?php echo $this->url(array('controller'=>'index','action'=>'index'),null, true);?>">
	<legend>Titulo</legend>
	<div class="form-group" id="anio-mes">
		<label for="input-anio-mes" class="col-xs-3 control-label">A&ntilde;o / Mes</label>
		<div class="col-xs-9">
			<select class="form-control" id="input-anio-mes" name="input-anio-mes">
				<option id="1" name="opcion1" >valor 1</option>
				<option id="2" name="opcion2" >valor 2</option>
				<option id="3" name="opcion3" >valor 3</option>
			</select>
		</div>
	</div>
	<div class="form-group" id="cuenta">
		<label for="input-cuenta" class="col-xs-3 control-label">Cuenta</label>
		<div class="col-xs-9">
			<input type="text" class="form-control" id="input-cuenta" name="input-cuenta" maxlength="12" value="">
		</div>
	</div>
	<div class="form-group">
		<div class="col-xs-offset-3 col-xs-9">
			<!--<button type="submit" class="btn btn-danger" name="aceptar" id="aceptar" value="aceptar">Aceptar</button>-->
			<button type="button" class="btn btn-warning" name="aceptar" id="aceptar" value="aceptar">Aceptar</button>
		</div>
	</div>
</form>
<div class="page-header">
        <h1>Panels</h1>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
              Panel content
            </div>
          </div>
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
              Panel content
            </div>
          </div>
        </div><!-- /.col-sm-4 -->
        <div class="col-sm-4">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
              Panel content
            </div>
          </div>
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
              Panel content
            </div>
          </div>
        </div><!-- /.col-sm-4 -->
        <div class="col-sm-4">
          <div class="panel panel-warning">
            <div class="panel-heading">
              <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
              Panel content
            </div>
          </div>
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
              Panel content
            </div>
          </div>
        </div><!-- /.col-sm-4 -->
      </div>

