<?php echo $this->doctype() ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  	<title>CE</title>
  	<!--<link type="image/x-icon" href="<?php //echo $this->BaseUrl() ?>/imagenes/favicon.ico" rel="icon" />-->
  	<?php
  		//	bootstrap
  		$this->headLink()->prependStylesheet($this->BaseUrl().'/bootstrap/css/bootstrap.css');
  		$this->headLink()->prependStylesheet($this->BaseUrl().'/css/menu.css');
	  	$this->headLink()->prependStylesheet($this->BaseUrl().'/css/style.css');
	  	$this->headLink()->prependStylesheet($this->BaseUrl().'/css/animate.css');
	  	$this->headLink()->prependStylesheet($this->BaseUrl().'/css/font-awesome.css');
	  	$this->headLink()->prependStylesheet($this->BaseUrl().'/css/overwrite.css');
	  	/*
	  	$this->headLink()->appendStylesheet($this->BaseUrl().'/css/bootstrap/css/bootstrap.css');
	  	$this->headLink()->appendStylesheet($this->BaseUrl().'/css/bootstrap/css/bootstrap-responsive.css');
	  	$this->headLink()->appendStylesheet($this->BaseUrl().'/css/bootstrap/css/docs.css');
			
  		$this->headScript()->prependFile($this->BaseUrl().'/js/prototype/prototype.js'); 
		*/
  		echo $this->headLink();
		echo $this->headScript();
		
		echo '<script src="'.$this->BaseUrl().'/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/jquery.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/jquery.easing.1.3.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/bootstrap.min.js"></script>';
		echo '<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyASm3CwaK9qtcZEWYa-iQwHaGi3gcosAJc&sensor=false"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/jquery.isotope.min.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/jquery.nicescroll.min.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/fancybox/jquery.fancybox.pack.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/skrollr.min.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/jquery.scrollTo-1.4.3.1-min.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/jquery.localscroll-1.2.7-min.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/stellar.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/jquery.appear.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/validate.js"></script>';
		echo '<script src="'.$this->BaseUrl().'/js/main.js"></script>';
	?>
	<script type="text/javascript">
		jQuery('.navbar').localScroll({hash:true, offset: {top: 0},duration: 800, easing:'easeInOutExpo'});
	</script>
</head>
	<body>
<!--	
		<div class="navbar navbar-fixed-top" role="navigation">
			<div class="navbar-wrapper">
				<div class="container">
					<div class="navbar navbar-inverse navbar-static-top">
			
						<div class="navbar-header">
							<a class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</a>
							<a class="navbar-brand" href="#">Bootstrap 3</a>
						</div>
						<div class="navbar-collapse collapse">
							<ul class="nav navbar-nav">
								<li class="active"><a href="#">Home</a></li>
								<li><a href="http://www.bootply.com" target="ext">About</a></li>
								<li><a href="#contact">Contact</a></li>
								<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li><a href="#">Action</a></li>
										<li><a href="#">Another action</a></li>
										<li><a href="#">Something else here</a></li>
										<li class="divider"></li>
										<li><a href="#">Separated link</a></li>
										<li><a href="#">One more separated link</a></li>
									</ul>
								</li>
							</ul>
						</div>
			
					</div>
				</div>
			</div>
		</div>
-->
	<!--<section id="header" class="appear"></section>-->
		<div class="navbar navbar-fixed-top" role="navigation" data-0="line-height:100px; height:100px; background-color:rgba(0, 0, 0, 0.8);" data-300="line-height:60px; height:60px; background-color:rgba(0,0,0,1);">
			 <div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="fa fa-bars color-white"></span>
					</button>
					<h1><a class="navbar-brand" href="index.html" data-0="line-height:50px;" data-300="line-height:0px;">Amoeba
					</a></h1>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav" data-0="margin-top:20px;" data-300="margin-top:5px;">
						<li class="active"><a href="index.html">Home</a></li>
						<li><a href="#section-about">About</a></li>
						<li><a href="#section-works">Portfolio</a></li>
						<li><a href="#section-contact">Contact</a></li>
					</ul>
				</div><!--/.navbar-collapse -->
			</div>
		</div>		
		<div class="page container">
			<div class="titulo"><h3><?php echo $this->titulo ?></h3></div>
			<div class="subtitulo"><?php echo $this->subtitulo ?></div>
		  	<?php echo $this->layout()->content ?>
		</div>
		<div class="blClear10"></div>
		<?php //echo $this->render('footer.phtml') ?>
		
		<?php 
			//echo '<script src="'.$this->BaseUrl().'/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>';
			echo '<script src="'.$this->BaseUrl().'/js/jquery.js"></script>';
			//echo '<script src="'.$this->BaseUrl().'/js/jquery.easing.1.3.js"></script>';
			echo '<script src="'.$this->BaseUrl().'/js/bootstrap.min.js"></script>';
			//echo '<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyASm3CwaK9qtcZEWYa-iQwHaGi3gcosAJc&sensor=false"></script>';
			//echo '<script src="'.$this->BaseUrl().'/js/jquery.isotope.min.js"></script>';
			//echo '<script src="'.$this->BaseUrl().'/js/jquery.nicescroll.min.js"></script>';
			echo '<script src="'.$this->BaseUrl().'/js/fancybox/jquery.fancybox.pack.js"></script>';
			echo '<script src="'.$this->BaseUrl().'/js/skrollr.min.js"></script>';
			echo '<script src="'.$this->BaseUrl().'/js/jquery.scrollTo-1.4.3.1-min.js"></script>';
			echo '<script src="'.$this->BaseUrl().'/js/jquery.localscroll-1.2.7-min.js"></script>';
			//echo '<script src="'.$this->BaseUrl().'/js/stellar.js"></script>';
			//echo '<script src="'.$this->BaseUrl().'/js/jquery.appear.js"></script>';
			echo '<script src="'.$this->BaseUrl().'/js/main.js"></script>';
		?>
	</body>
</html>
