<!--echo $this->doctype()-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="shortcut icon" href="../../assets/ico/favicon.ico">-->

    <!--<title>Fixed Top Navbar Example for Bootstrap</title>-->

  	<?php
  		//	bootstrap
  		$this->headLink()->prependStylesheet($this->BaseUrl().'/bootstrap-3.1.1-dist/css/bootstrap.min.css');
  		//$this->headScript()->prependFile($this->BaseUrl().'/bootstrap-3.1.1-dist/js/bootstrap.min.js'); 
  		
  		//$this->headLink()->prependStylesheet($this->BaseUrl().'/css/menu.css');
	  	/*
	  	$this->headLink()->appendStylesheet($this->BaseUrl().'/css/bootstrap/css/bootstrap.css');
	  	$this->headLink()->appendStylesheet($this->BaseUrl().'/css/bootstrap/css/bootstrap-responsive.css');
	  	$this->headLink()->appendStylesheet($this->BaseUrl().'/css/bootstrap/css/docs.css');
			
  		*/
  		$this->headLink()->prependStylesheet($this->BaseUrl().'/css/style.css');
  		echo $this->headLink();
		
	?>
</head>
<body>

    <!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Project name</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">Home</a></li>
					<li><a href="#about">About</a></li>
					<li><a href="#contact">Contact</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
							<li role="presentation" class="dropdown-header">Dropdown header</li>
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li role="presentation" class="divider"></li>
							<li class="dropdown-header">Nav header</li>
							<li><a href="#">Separated link</a></li>
							<li><a href="#">One more separated link</a></li>
						</ul>
					</li>
				</ul>
          		<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="user-logeado"><?php print $this->nombre_usuario ?> </span><span class="glyphicon glyphicon-user"></span></a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
							<li><a href="#"><span class="glyphicon glyphicon-edit"></span>  Perfil</a></li>
							<li><a href="<?php echo $this->url(array('controller'=>'logout','action'=>'index'),null, true);?>"><span class="glyphicon glyphicon-off"></span>  Logout</a></li>
						</ul>
					</li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
    </div>

	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<?php 
					if($this->error == 1){
						echo $this->render('error.phtml');
					} 
				?>
				<?php 
					if($this->hay_mensaje == 1){
						echo $this->render('mensaje.phtml');
					}
				?>
			</div>
			<div class="col-xs-12">
				<?php echo $this->layout()->content ?>
			</div>
		</div>
<!-- Main component for a primary marketing message or call to action -->
<!--
<div class="jumbotron">
	<h1>Navbar example</h1>
	<p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
	<p>To see the difference between static and fixed top navbars, just scroll.</p>
	<p>
	<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
	</p>
</div>
-->
	</div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script src="<?php print $this->BaseUrl().'/jquery-1.11.1/jquery.js'?>"></script>
	<script src="<?php print $this->BaseUrl().'/bootstrap-3.1.1-dist/js/bootstrap.min.js' ?>"></script>
	<?php echo $this->headScript();?>
  </body>
</html>
